<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeederManga extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'title' => 'One Piece',
                'image' => 'https://example.com/onepiece.jpg',
                'description' => 'Mengisahkan perjalanan Monkey D. Luffy yang bermimpi menjadi Raja Bajak Laut dengan mencari harta karun legendaris, One Piece. Ia membentuk kru dengan berbagai karakter unik, menjelajahi lautan dan menghadapi berbagai musuh kuat.',
                'penerbit' => 'Shueisha',
                'author' => 'Eiichiro Oda',
                'price' => 35000,
                'category_id' => 1,
                'stock' => 100,
                'publish_date' => '1997-07-22',
                'discount' => 10,
            ],
            [
                'title' => 'Naruto',
                'image' => 'https://example.com/naruto.jpg',
                'description' => 'Cerita tentang Naruto Uzumaki, seorang ninja muda yang berusaha mendapatkan pengakuan dari desa dan menjadi Hokage, pemimpin desa. Di tengah perjuangannya, ia menyimpan kekuatan besar yang dapat menghancurkan dunia.',
                'penerbit' => 'Shueisha',
                'author' => 'Masashi Kishimoto',
                'price' => 40000,
                'category_id' => 1,
                'stock' => 120,
                'publish_date' => '1999-09-21',
                'discount' => 15,
            ],
            [
                'title' => 'Attack on Titan',
                'image' => 'https://example.com/attackontitan.jpg',
                'description' => 'Dalam dunia yang dikelilingi oleh tembok besar untuk melindungi manusia dari raksasa pemangsa, Eren Yeager bergabung dengan pasukan untuk melawan para Titan setelah desanya dihancurkan oleh salah satu Titan besar.',
                'penerbit' => 'Kodansha',
                'author' => 'Hajime Isayama',
                'price' => 45000,
                'category_id' => 1,
                'stock' => 80,
                'publish_date' => '2009-09-09',
                'discount' => 5,
            ],
            [
                'title' => 'Demon Slayer',
                'image' => 'https://example.com/demonslayer.jpg',
                'description' => 'Tanjiro Kamado, seorang anak yang kehilangan keluarganya karena serangan iblis, berusaha menyelamatkan adiknya, Nezuko, yang berubah menjadi iblis. Ia bergabung dengan pasukan pemburu iblis untuk membasmi semua iblis yang ada.',
                'penerbit' => 'Shueisha',
                'author' => 'Koyoharu Gotouge',
                'price' => 50000,
                'category_id' => 1,
                'stock' => 150,
                'publish_date' => '2016-02-15',
                'discount' => 20,
            ],
            [
                'title' => 'My Hero Academia',
                'image' => 'https://example.com/myheroacademia.jpg',
                'description' => 'Izuku Midoriya, seorang anak tanpa kekuatan (Quirk) di dunia yang sebagian besar orang memilikinya, bermimpi menjadi pahlawan. Setelah bertemu dengan pahlawan legendaris All Might, ia mendapat kesempatan untuk mewujudkan impiannya.',
                'penerbit' => 'Shueisha',
                'author' => 'Kohei Horikoshi',
                'price' => 37000,
                'category_id' => 1,
                'stock' => 200,
                'publish_date' => '2014-07-07',
                'discount' => 10,
            ],
            [
                'title' => 'Jujutsu Kaisen',
                'image' => 'https://example.com/jujutsukaisen.jpg',
                'description' => 'Yuji Itadori, seorang remaja dengan kemampuan fisik luar biasa, terlibat dalam dunia jujutsu setelah menelan benda terkutuk dan menjadi tuan dari roh jahat yang bisa menghancurkan dunia.',
                'penerbit' => 'Shueisha',
                'author' => 'Gege Akutami',
                'price' => 42000,
                'category_id' => 1,
                'stock' => 180,
                'publish_date' => '2018-03-05',
                'discount' => 12,
            ],
            [
                'title' => 'Fullmetal Alchemist',
                'image' => 'https://example.com/fullmetalalchemist.jpg',
                'description' => 'Edward dan Alphonse Elric adalah dua bersaudara yang mencoba menghidupkan kembali ibu mereka dengan alkimia, namun mereka gagal dan kehilangan bagian tubuh mereka. Mereka berusaha mencari Batu Bertuah untuk mengembalikan keadaan mereka.',
                'penerbit' => 'Square Enix',
                'author' => 'Hiromu Arakawa',
                'price' => 48000,
                'category_id' => 1,
                'stock' => 60,
                'publish_date' => '2001-01-25',
                'discount' => 5,
            ],
            [
                'title' => 'Death Note',
                'image' => 'https://example.com/deathnote.jpg',
                'description' => 'Light Yagami, seorang siswa cerdas, menemukan sebuah buku yang dapat membunuh siapa saja yang namanya tertulis di dalamnya. Ia memutuskan untuk menciptakan dunia baru dengan menghukum orang-orang jahat, namun ada detektif bernama L yang mencoba menghentikan aksinya.',
                'penerbit' => 'Shueisha',
                'author' => 'Tsugumi Ohba, Takeshi Obata',
                'price' => 55000,
                'category_id' => 1,
                'stock' => 90,
                'publish_date' => '2003-12-02',
                'discount' => 8,
            ],
            [
                'title' => 'Bleach',
                'image' => 'https://example.com/bleach.jpg',
                'description' => 'Ichigo Kurosaki, seorang remaja yang memiliki kemampuan melihat roh, mendapatkan kekuatan sebagai Soul Reaper dan harus melindungi dunia manusia dari roh-roh jahat yang disebut Hollow.',
                'penerbit' => 'Shueisha',
                'author' => 'Tite Kubo',
                'price' => 43000,
                'category_id' => 1,
                'stock' => 110,
                'publish_date' => '2001-08-07',
                'discount' => 18,
            ],
            [
                'title' => 'Dragon Ball',
                'image' => 'https://example.com/dragonball.jpg',
                'description' => 'Goku, seorang anak dengan ekor monyet, memiliki kekuatan luar biasa. Ia berpetualang mencari bola naga yang dapat mengabulkan permintaan apapun, sambil berlatih untuk menjadi petarung terbaik di dunia.',
                'penerbit' => 'Shueisha',
                'author' => 'Akira Toriyama',
                'price' => 38000,
                'category_id' => 1,
                'stock' => 130,
                'publish_date' => '1984-12-03',
                'discount' => 7,
            ],
            [
                'title' => 'One Punch Man',
                'image' => 'https://example.com/onepunchman.jpg',
                'description' => 'Saitama adalah pahlawan yang bisa mengalahkan musuh dengan satu pukulan. Namun, ia merasa bosan karena tidak ada musuh yang bisa memberinya tantangan. Ia berusaha mencari lawan yang lebih kuat sambil bertugas sebagai pahlawan.',
                'penerbit' => 'Shueisha',
                'author' => 'ONE, Yusuke Murata',
                'price' => 39000,
                'category_id' => 1,
                'stock' => 160,
                'publish_date' => '2012-06-14',
                'discount' => 10,
            ],
            [
                'title' => 'Hunter x Hunter',
                'image' => 'https://example.com/hunterxhunter.jpg',
                'description' => 'Gon Freecss berusaha untuk menemukan ayahnya yang telah lama hilang dengan menjadi seorang Hunter, orang-orang terpilih yang memiliki izin untuk melakukan hal-hal luar biasa. Selama perjalanan, ia bertemu dengan teman-teman dan menghadapi ujian berat.',
                'penerbit' => 'Shueisha',
                'author' => 'Yoshihiro Togashi',
                'price' => 42000,
                'category_id' => 1,
                'stock' => 140,
                'publish_date' => '1998-03-03',
                'discount' => 5,
            ],
            [
                'title' => 'Tokyo Ghoul',
                'image' => 'https://example.com/tokyoghoul.jpg',
                'description' => 'Ken Kaneki, seorang remaja yang menjadi setengah ghoul setelah kecelakaan, harus beradaptasi dengan dunia baru yang penuh dengan ancaman. Ia harus bertahan hidup di antara manusia dan ghoul yang saling berburu.',
                'penerbit' => 'Shueisha',
                'author' => 'Sui Ishida',
                'price' => 46000,
                'category_id' => 1,
                'stock' => 200,
                'publish_date' => '2011-09-08',
                'discount' => 15,
            ],
            [
                'title' => 'Black Clover',
                'image' => 'https://example.com/blackclover.jpg',
                'description' => 'Asta, seorang anak yang lahir tanpa sihir di dunia yang hampir semua orang memilikinya, berusaha untuk menjadi Wizard King. Bersama temannya Yuno, yang sangat berbakat, ia berjuang untuk mencapai impiannya.',
                'penerbit' => 'Shueisha',
                'author' => 'Yūki Tabata',
                'price' => 44000,
                'category_id' => 1,
                'stock' => 150,
                'publish_date' => '2015-02-16',
                'discount' => 10,
            ],
            [
                'title' => 'Fairy Tail',
                'image' => 'https://example.com/fairytail.jpg',
                'description' => 'Lucy Heartfilia bergabung dengan guild penyihir yang kuat, Fairy Tail. Bersama dengan Natsu Dragneel dan teman-teman lainnya, mereka menjalani berbagai petualangan penuh aksi dan persahabatan.',
                'penerbit' => 'Kodansha',
                'author' => 'Hiro Mashima',
                'price' => 43000,
                'category_id' => 1,
                'stock' => 170,
                'publish_date' => '2006-12-02',
                'discount' => 12,
            ],
            [
                'title' => 'Sword Art Online',
                'image' => 'https://example.com/swordartonline.jpg',
                'description' => 'Kazuto Kirigaya terjebak dalam dunia virtual game dan harus berjuang untuk keluar dari permainan tersebut. Bersama dengan teman-temannya, ia berusaha untuk mengalahkan berbagai level dan monster untuk bisa kembali ke dunia nyata.',
                'penerbit' => 'ASCII Media Works',
                'author' => 'Reki Kawahara',
                'price' => 50000,
                'category_id' => 1,
                'stock' => 90,
                'publish_date' => '2009-04-10',
                'discount' => 8,
            ],
            [
                'title' => 'Nisekoi',
                'image' => 'https://example.com/nisekoi.jpg',
                'description' => 'Raku Ichijou, seorang anak laki-laki dari keluarga Yakuza, berusaha menjaga janji yang dibuat bersama seorang gadis misterius saat kecil. Ia kemudian terlibat dalam hubungan rumit dengan dua gadis yang berbeda.',
                'penerbit' => 'Shueisha',
                'author' => 'Naoshi Komi',
                'price' => 38000,
                'category_id' => 1,
                'stock' => 110,
                'publish_date' => '2011-11-23',
                'discount' => 10,
            ],
            [
                'title' => 'Kaguya-sama: Love Is War',
                'image' => 'https://example.com/kaguya.jpg',
                'description' => 'Kaguya Shinomiya dan Miyuki Shirogane, dua siswa cerdas di sekolah elit, saling menyukai namun enggan mengakuinya. Mereka terlibat dalam perang psikologis untuk membuat satu sama lain mengungkapkan perasaan mereka.',
                'penerbit' => 'Shueisha',
                'author' => 'Aka Akasaka',
                'price' => 37000,
                'category_id' => 1,
                'stock' => 160,
                'publish_date' => '2015-05-19',
                'discount' => 5,
            ],
            [
                'title' => 'Yona of the Dawn',
                'image' => 'https://example.com/yonaofthedawn.jpg',
                'description' => 'Yona, seorang putri kerajaan yang hidup damai, terpaksa melarikan diri setelah kerajaan yang ia cintai dihancurkan. Dalam perjalanan melarikan diri, ia mencari teman-teman untuk membantunya merebut kembali takhta.',
                'penerbit' => 'Hakusensha',
                'author' => 'Mizuho Kusanagi',
                'price' => 45000,
                'category_id' => 1,
                'stock' => 130,
                'publish_date' => '2009-08-05',
                'discount' => 15,
            ],
        ];

        foreach ($books as $book) {
            DB::table('book')->insert($book);
        }
    }
}
